apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - name: http
    port: 4000
    targetPort: 4000
    nodePort: 30036
    protocol: TCP
